import numpy as np
# import matplotlib.pyplot as plt
# a = np.arange(1,11)
# print('a ==> {a}')
# print(f'a ==> {a}')
# print(f'dimensions of the array a ==> {a.ndim}')
# print(f'data type of elements of array a ==> {a.dtype}')
# print(f'size of the array a ==> {a.size}')
# print(f'shape of the array a ==> {a.shape}')

a = np.arange(1,10).reshape(3,3)
print(f"Original 2-D array ==> \n {a}")
print(f'dimensions of the array a ==> {a.ndim}')
# print(f"Elements prsent at 0-diagonal ==> {np.diag(a,k=0)}")
# print(f"Elements prsent at 1-diagonal ==> {np.diag(a,k=1)}")
# print(f"Elements prsent at 2-diagonal ==> {np.diag(a,k=2)}")
# print(f"Elements prsent at -1-diagonal ==> {np.diag(a,k=-1)}")
# print(f"Elements prsent at -2-diagonal ==> {np.diag(a,k=-2)}")
# print(f"Elements prsent at 3-diagonal ==> {np.diag(a,k=3)}")
a = np.array([10,20,30,40])
print(f'dimensions of the array a ==> {a.ndim}')
# print(" array ")
print(np.diag(a,k=2))
print(np.diag(a,k=2))
# s = np.random.uniform(20,30,size=1000000)

# a = np.array([10,20,30,40,50])
# print(a[3])
# print(a[-1])

# a = np.array([[10,20,30],[40,50,60]])
# print(f"Shape of the array a : {a.shape}")
# print("To Access the element 50")
# print(f"a[1][1] ==> {a[1][1]}")
# print(f"a[1][-2] ==> {a[1][-2]}")
# print(f"a[-1][2] ==> {a[-1][-2]}")
# print(f"a[-1][1] ==> {a[-1][1]}")


# l = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
# a = np.array(l)
# print(f"Shape of the array a ==> {a.shape}")
# print("To access the element 14 from the 3-D array")
# print(f"a[1][1][1] ==> {a[1][1][1]}")
# print(f"a[-1][-2][-2] ==> {a[-1][-2][-2]}")
# print(f"a[1][-2][-2] ==> {a[1][-2][-2]}")
# print(f"a[-1][1][-2] ==> {a[-1][1][-2]}")