select CLIENT_MASTER.NAME,	CLIENT_MASTER.CLIENTNO,	SALES_ORDER.ORDERNO,	SALES_ORDER_DETAILS.PRODUCTNO,	PRODUCT_MASTER.DESCRIPTION
	FROM CLIENT_MASTER
	join SALES_ORDER ON CLIENT_MASTER.CLIENTNO = SALES_ORDER.CLIENTNO
	join SALES_ORDER_DETAILS ON SALES_ORDER.ORDERNO = SALES_ORDER_DETAILS.ORDERNO
	join PRODUCT_MASTER ON  SALES_ORDER_DETAILS.PRODUCTNO=PRODUCT_MASTER.PRODUCTNO